(
[
"xxxxxxxxxxxxxxxxxxxx",
"x---------------3---",
"xxx-xxxxxxxxxxxxxxxx",
"xxx-xxx-xxx----xxxxx",
"x-----------xx-----x",
"xxxxxxxxxx-xxxxxxxxx",
"x------------------x",
"xxxxxxxx-xxxxxxxxxxx",
"x------------------x",
"xxxxxxxxxxxxxxxxxx-x",
"x--------1-------x-x",
"xxxxxx-xxxxxxxxxxx-x",
"x------------------x",
"xxxxxxxxxx-xxxxxxxxx",
"x--2---------------x",
"xxxxxxxxxxxxxxxxxxxx"
],
"rldurul"
)
